"use client";
import { useEffect, useMemo, useState } from "react";

type Mode=0|1|2|3;
type Item={id:string;description:string;amount:number;selected:Mode;grossProfitRate?:number};
type Section={id:string;title:string;kind:"no-charge"|"charge"|"deduction"|"mt"|"mt7";items:Item[]};
type Estimate={project:Record<string,string>;vatRate:number;sections:Section[]};
type ProfitRow={id:string;description:string;cost:number;rate:number;profit:number;total:number};
type ProfitReport={rows:ProfitRow[];overflowCount:number;totalCost:number;totalProfit:number;totalWithProfit:number};
type SummarySection={id:string;title:string;kind:"no-charge"|"charge";items:{id:string;description:string;amount:number}[];total:number};
type DeductionLine={id:string;description:string;amount:number;mode:Mode};
type SummaryReport={sections:SummarySection[];deductionItems:DeductionLine[];totals:Record<string,number>};
type SubtopicReport={chargeSections:SummarySection[];peaSections:SummarySection[];deductionItems:DeductionLine[];totals:Record<string,number>};
type Result={totals:Record<string,number>;profitReport:ProfitReport;summaryReport:SummaryReport;subtopicReport:SubtopicReport};
type HotlineValue=number|"";
type HotlineInput={regularDays:HotlineValue;regularRate:HotlineValue;holidayDays:HotlineValue;holidayRate:HotlineValue;hotstickDays:HotlineValue;hotstickRate:HotlineValue;bucket2233Days:HotlineValue;bucket2233Rate:HotlineValue;bucket115Days:HotlineValue;bucket115Rate:HotlineValue;waterTruckDays:HotlineValue;waterTruckRate:HotlineValue;allowanceDays:HotlineValue;allowanceRate:HotlineValue;lodgingDays:HotlineValue;lodgingRate:HotlineValue;hotstickKm:HotlineValue;hotstickFuelPrice:HotlineValue;bucketKm:HotlineValue;bucketFuelPrice:HotlineValue;bucketWaterKm:HotlineValue;bucketWaterFuelPrice:HotlineValue;waterTruckKm:HotlineValue;waterTruckFuelPrice:HotlineValue};
type HotlineResult={rows:Record<string,number>;total:number};
type Employee={id:string;position:string;prefix:string;firstName:string;lastName:string;phone:string;fullName:string};
type WorkItem={id:string;description:string;quantity:number;unitPrice:number;labor:number};
type WorkTemplate={id:string;sheetName:string;group:string;title:string;note:string;quote:string;custom:boolean;items:WorkItem[]};
const API=process.env.NEXT_PUBLIC_API_URL??"";
const labels:Record<string,string>={jobName:"ชื่องาน",address:"ที่อยู่",subdistrict:"ตำบล",district:"อำเภอ",province:"จังหวัด",postalCode:"รหัสไปรษณีย์",drawingNo:"เลขที่แบบ",wbs:"WBS",requestNo:"เลขที่คำร้อง",requestDate:"วันที่คำร้อง",surveyor:"ผู้สำรวจ",estimator:"ผู้ประมาณการ",reviewer:"ผู้ตรวจสอบ"};
const money=(n=0)=>new Intl.NumberFormat("th-TH",{minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
const moneyInput=(value:HotlineValue)=>value===""?"":new Intl.NumberFormat("en-US",{maximumFractionDigits:2}).format(value);
const parseMoneyInput=(value:string):HotlineValue=>value.trim()===""?"":Number(value.replace(/,/g,""));
const profitTextSize=(text:string)=>text.length<=30?16:text.length<=45?15:text.length<=60?14.25:13.75;

export default function Page(){
 const [data,setData]=useState<Estimate|null>(null); const [employees,setEmployees]=useState<Employee[]>([]); const [result,setResult]=useState<Result|null>(null); const [tab,setTab]=useState("project"); const [activeSectionId,setActiveSectionId]=useState(""); const [error,setError]=useState("");
 const emptyEmployee={id:"",position:"",prefix:"นาย",firstName:"",lastName:"",phone:""}; const [employeeDraft,setEmployeeDraft]=useState(emptyEmployee); const [editingEmployeeId,setEditingEmployeeId]=useState("");
 useEffect(()=>{fetch(`${API}/api/estimate/template`).then(r=>r.json()).then(setData).catch(()=>setError("เชื่อมต่อ backend ไม่ได้ กรุณาเปิด API ที่พอร์ต 4000"));},[]);
 useEffect(()=>{fetch(`${API}/api/employees`).then(r=>r.json()).then(setEmployees).catch(()=>setError("โหลดฐานข้อมูลรายชื่อพนักงานไม่สำเร็จ"));},[]);
 useEffect(()=>{if(!data)return; const t=setTimeout(()=>fetch(`${API}/api/estimate/calculate`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)}).then(r=>r.json()).then(setResult).catch(()=>setError("คำนวณไม่สำเร็จ")),180);return()=>clearTimeout(t)},[data]);
 useEffect(()=>{if(!data||!result)return;const total=result.profitReport.totalProfit;let changed=false;const sections=data.sections.map(section=>({...section,items:section.items.map(item=>{if(!isGrossProfitLine(item.description)||item.amount===total)return item;changed=true;return {...item,amount:total};})}));if(changed)setData({...data,sections});},[result?.profitReport.totalProfit]);
 const selected=useMemo(()=>data?.sections.reduce((n,s)=>n+s.items.filter(i=>i.selected).length,0)??0,[data]);
 if(!data)return <main className="loading">กำลังโหลดแบบประมาณการ…<p>{error}</p></main>;
 const updateItem=(sid:string,iid:string,key:keyof Item,value:string|number)=>setData(d=>!d?d:{...d,sections:d.sections.map(s=>s.id!==sid?s:{...s,items:s.items.map(i=>i.id!==iid?i:{...i,[key]:value})})});
 const addItem=(sid:string)=>setData(d=>!d?d:{...d,sections:d.sections.map(s=>s.id!==sid?s:{...s,items:[...s.items,{id:crypto.randomUUID(),description:"รายการใหม่",amount:0,selected:1}]})});
 const deleteItem=(sid:string,item:Item)=>{if(!window.confirm(`ลบรายการ “${item.description}” หรือไม่?`))return;setData(current=>!current?current:{...current,sections:current.sections.map(section=>section.id!==sid?section:{...section,items:section.items.filter(row=>row.id!==item.id)})});};
 const saveEmployee=async()=>{const method=editingEmployeeId?"PUT":"POST";const url=editingEmployeeId?`${API}/api/employees/${editingEmployeeId}`:`${API}/api/employees`;const body=editingEmployeeId?{position:employeeDraft.position,prefix:employeeDraft.prefix,firstName:employeeDraft.firstName,lastName:employeeDraft.lastName,phone:employeeDraft.phone}:employeeDraft;const response=await fetch(url,{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!response.ok){setError((await response.json()).message??"บันทึกรายชื่อไม่สำเร็จ");return;}const saved:Employee=await response.json();setEmployees(current=>editingEmployeeId?current.map(item=>item.id===editingEmployeeId?saved:item):[...current,saved]);setEmployeeDraft(emptyEmployee);setEditingEmployeeId("");};
 const editEmployee=(employee:Employee)=>{setEditingEmployeeId(employee.id);setEmployeeDraft({id:employee.id,position:employee.position,prefix:employee.prefix,firstName:employee.firstName,lastName:employee.lastName,phone:employee.phone});};
 const deleteEmployee=async(employee:Employee)=>{if(!window.confirm(`ลบ ${employee.fullName} ออกจากฐานข้อมูลหรือไม่?`))return;const response=await fetch(`${API}/api/employees/${employee.id}`,{method:"DELETE"});if(response.ok)setEmployees(current=>current.filter(item=>item.id!==employee.id));else setError("ลบรายชื่อไม่สำเร็จ");};
 const exportJson=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download=`ประมาณการ-${data.project.requestNo||"draft"}.json`;a.click()};
 const isGrossProfitLine=(description:string)=>description.replace(/\s+/g,"").toLowerCase().includes("กำไรขั้นต้น");
 const createProfit=async()=>{
  setError("");
  try{
   const response=await fetch(`${API}/api/estimate/calculate`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});
   if(!response.ok)throw new Error("calculate failed");
   const fresh:Result=await response.json();
   setResult(fresh);
   setData(current=>!current?current:{...current,sections:current.sections.map(section=>({...section,items:section.items.map(item=>isGrossProfitLine(item.description)?{...item,amount:fresh.profitReport.totalProfit}:item)}))});
   setTab("profit");
 }catch{setError("สร้างกำไรขั้นต้นไม่สำเร็จ");}
 };
 const createSummary=async()=>{
  setError("");
  try{
   const firstResponse=await fetch(`${API}/api/estimate/calculate`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});
   if(!firstResponse.ok)throw new Error("profit calculation failed");
   const first:Result=await firstResponse.json();
   const updated={...data,sections:data.sections.map(section=>({...section,items:section.items.map(item=>isGrossProfitLine(item.description)?{...item,amount:first.profitReport.totalProfit}:item)}))};
   const finalResponse=await fetch(`${API}/api/estimate/calculate`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(updated)});
   if(!finalResponse.ok)throw new Error("summary calculation failed");
   const finalResult:Result=await finalResponse.json();
   setData(updated); setResult(finalResult); setTab("summary-report");
 }catch{setError("สร้างสรุปค่าใช้จ่ายไม่สำเร็จ");}
 };
 const applyHotlineTotal=(total:number)=>setData(current=>{
  if(!current)return current;
  let changed=false;
  const sections=current.sections.map(section=>({...section,items:section.items.map(item=>{
   const normalized=item.description.replace(/\s+/g,"");
   const isHotline=item.id==="fee-hotline"||normalized.includes("บริการด้านฮอตไลน์")||normalized.includes("บริการด้านฮอทไลน์");
   if(isHotline&&(item.amount!==total||(total>0&&item.selected!==1))){changed=true;return {...item,amount:total,selected:total>0?1:item.selected};}
   return item;
  })}));
  return changed?{...current,sections}:current;
 });
 return <main className={tab==="costs"?"costsView":""}>
  <header><div><span className="eyebrow">PEA ESTIMATE WORKSPACE</span><h1>ระบบประมาณการค่าใช้จ่าย</h1><p>ถอด workflow จากไฟล์ ออกเอกสาร.xlsm</p></div><div className="actions"><button className="ghost" onClick={exportJson}>บันทึก JSON</button><button onClick={()=>window.print()}>พิมพ์ / PDF</button></div></header>
  <section className="stats"><div><span>รายการที่เลือก</span><strong>{selected}</strong></div><div><span>ฐานคิด VAT</span><strong>฿{money(result?.totals.vatBase)}</strong></div><div><span>VAT 7%</span><strong>฿{money(result?.totals.vat)}</strong></div><div className="accent"><span>ยอดชำระสุทธิ</span><strong>฿{money(result?.totals.payable)}</strong></div></section>
  <nav>{[["project","ข้อมูลงาน"],["costs","รายการประมาณการ"],["work-templates","หม้อแปลง / Turnkey"],["hotline","ค่าบริการฮอทไลน์"],["profit","กำไรขั้นต้น"],["summary-report","สรุปค่าใช้จ่าย"]].map(([k,v])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{v}</button>)}</nav>
  {tab==="costs"&&<section className="estimateIntro"><div><span className="eyebrow">ESTIMATE WORKSPACE</span><h2>รายการประมาณการ</h2><p>เลือกและแก้ไขรายการได้จากหน้าเดียว ยอดจากกำไรขั้นต้นและ Hotline เชื่อมกลับอัตโนมัติ</p></div><div className="linkedCards"><div><span>กำไรขั้นต้น</span><b>฿{money(result?.profitReport.totalProfit)}</b><small>เชื่อมยอดอัตโนมัติ</small></div><div><span>ค่าบริการด้านฮอตไลน์</span><b>฿{money(data.sections.flatMap(section=>section.items).find(item=>item.id==="fee-hotline")?.amount)}</b><small>เชื่อมยอดอัตโนมัติ</small></div></div></section>}
  <div className="persistentHotline" hidden={tab!=="hotline"}><HotlineWorkspace project={data.project} onApply={applyHotlineTotal}/></div>
  <div className="persistentWorkTemplates" hidden={tab!=="work-templates"}><WorkTemplateWorkspace project={data.project}/></div>
  {tab==="costs"&&<div className="summaryModuleAction moduleAction"><div><b>Module1 · สรุปค่าใช้จ่าย</b><span>สร้าง summary_report และ summary_subtopic_table</span></div><button onClick={createSummary}>สร้างสรุปค่าใช้จ่าย →</button></div>}
  {tab==="summary-report"&&result&&<SummaryWorkspace data={data} summary={result.summaryReport} subtopic={result.subtopicReport} onBack={()=>setTab("costs")}/>} 
  {tab==="project"&&<><section className="panel"><div className="panelTitle"><div><h2>ข้อมูลโครงการ</h2><p>ข้อมูลต้นทางจากชีต “หน้าหลัก”</p></div></div><div className="formGrid">{Object.entries(data.project).filter(([k])=>!(["surveyor","estimator","reviewer"].includes(k))).map(([k,v])=><label key={k} className={k==="jobName"||k==="address"?"wide":""}><span>{labels[k]??k}</span><input type={k==="requestDate"?"date":"text"} value={v} onChange={e=>setData({...data,project:{...data.project,[k]:e.target.value}})}/></label>)}</div><div className="personnelSection"><div><span className="eyebrow">ผู้รับผิดชอบงาน</span><h3>เลือกพนักงานสำหรับเอกสาร</h3></div><div className="personnelRow">{(["surveyor","estimator","reviewer"] as const).map(k=><label key={k}><span>{labels[k]}</span><select value={data.project[k]} onChange={e=>setData({...data,project:{...data.project,[k]:e.target.value}})}><option value="">เลือกรายชื่อพนักงาน</option>{employees.map(employee=><option key={employee.id} value={employee.fullName}>{employee.fullName} · {employee.position} ({employee.id})</option>)}</select></label>)}</div></div></section><details className="panel employeeManager"><summary><div><h2>จัดการรายชื่อพนักงาน</h2><p>เพิ่ม แก้ไข หรือลบรายชื่อที่ใช้ใน dropdown</p></div><span>เปิดจัดการรายชื่อ</span></summary><div className="employeeManagerBody"><div className="employeeAdd"><input placeholder="เลขประจำตัว" disabled={Boolean(editingEmployeeId)} value={employeeDraft.id} onChange={e=>setEmployeeDraft({...employeeDraft,id:e.target.value})}/><input placeholder="ตำแหน่ง" value={employeeDraft.position} onChange={e=>setEmployeeDraft({...employeeDraft,position:e.target.value})}/><select value={employeeDraft.prefix} onChange={e=>setEmployeeDraft({...employeeDraft,prefix:e.target.value})}><option>นาย</option><option>นาง</option><option>นางสาว</option></select><input placeholder="ชื่อ" value={employeeDraft.firstName} onChange={e=>setEmployeeDraft({...employeeDraft,firstName:e.target.value})}/><input placeholder="นามสกุล" value={employeeDraft.lastName} onChange={e=>setEmployeeDraft({...employeeDraft,lastName:e.target.value})}/><input placeholder="เบอร์โทร" value={employeeDraft.phone} onChange={e=>setEmployeeDraft({...employeeDraft,phone:e.target.value})}/><button type="button" onClick={saveEmployee}>{editingEmployeeId?"บันทึกการแก้ไข":"เพิ่มรายชื่อ"}</button>{editingEmployeeId&&<button type="button" className="ghost" onClick={()=>{setEditingEmployeeId("");setEmployeeDraft(emptyEmployee)}}>ยกเลิก</button>}</div><div className="employeeList">{employees.map(employee=><div key={employee.id}><div><b>{employee.fullName}</b><span>{employee.position} · {employee.id} · {employee.phone}</span></div><div><button type="button" className="ghost small" onClick={()=>editEmployee(employee)}>แก้ไข</button><button type="button" className="ghost small danger" onClick={()=>deleteEmployee(employee)}>ลบ</button></div></div>)}</div></div></details></>}
  {tab==="costs"&&<div className="sections"><div className="sectionNavigator"><div className="sectionNavigatorHead"><div><span className="eyebrow">หมวดค่าใช้จ่าย</span><h2>เลือกหมวดที่ต้องการแก้ไข</h2></div></div><div className="sectionTabs">{data.sections.map(section=>{const active=(activeSectionId||data.sections[0]?.id)===section.id;const chosen=section.items.filter(item=>item.selected!==0).length;const total=section.items.filter(item=>item.selected!==0).reduce((sum,item)=>sum+item.amount,0);return <button type="button" key={section.id} className={active?"active":""} onClick={()=>setActiveSectionId(section.id)}><span>{section.title}</span><small>{chosen} รายการ</small><b>{money(total)} บาท</b></button>})}</div></div>{data.sections.filter(section=>section.id===(activeSectionId||data.sections[0]?.id)).map(section=><section className="panel estimateSection" key={section.id}><div className="panelTitle"><div><span className={`tag ${section.kind}`}>หมวดที่เลือก</span><h2>{section.title}</h2><p>{section.items.length} รายการ · เลือก {section.items.filter(item=>item.selected!==0).length} รายการ</p></div><button className="small ghost" onClick={()=>addItem(section.id)}>+ เพิ่มรายการ</button></div><div className="table"><div className="tr head"><span>{section.kind==="deduction"?"วิธีหัก":"เลือก"}</span><span>รายละเอียด</span><span>จำนวนเงิน (บาท)</span><span>กำไร (%)</span><span></span></div>{section.items.map(item=>{const calculated=isGrossProfitLine(item.description)||item.id==="fee-hotline";return <div className={`tr ${calculated?"calculatedRow":""}`} key={item.id}>{section.kind==="deduction"?<select aria-label="วิธีหักค่าใช้จ่าย" value={item.selected} onChange={e=>updateItem(section.id,item.id,"selected",Number(e.target.value))}><option value={0}>ไม่เลือก</option><option value={1}>แสดงข้อมูล</option><option value={2}>หักหลัง VAT</option><option value={3}>หักก่อน VAT</option></select>:<label className="checkSelect" aria-label={item.selected===1?"ยกเลิกเลือกรายการ":"เลือกรายการ"}><input type="checkbox" checked={item.selected===1} onChange={e=>updateItem(section.id,item.id,"selected",e.target.checked?1:0)}/></label>}<input value={item.description} onChange={e=>updateItem(section.id,item.id,"description",e.target.value)}/><div className="calculatedAmount"><input className="num" type="text" inputMode="decimal" value={moneyInput(item.amount)} readOnly={calculated} onChange={e=>updateItem(section.id,item.id,"amount",Number(parseMoneyInput(e.target.value)||0))}/>{calculated&&<small>คำนวณอัตโนมัติ</small>}</div><input className="num" type="number" step="1" value={(item.grossProfitRate??0)*100} onChange={e=>updateItem(section.id,item.id,"grossProfitRate",Number(e.target.value)/100)}/><button type="button" className="rowDelete" onClick={()=>deleteItem(section.id,item)}>ลบ</button></div>})}</div></section>)}</div>}
  {tab==="profit"&&<section className="profitWorkspace"><div className="profitToolbar"><button className="ghost" onClick={()=>setTab("costs")}>← กลับ tableexpend</button><span>{result?.profitReport.rows.length??0} รายการ{result?.profitReport.overflowCount?` · เกิน template ${result.profitReport.overflowCount} รายการ`:""}</span><button onClick={()=>window.print()}>พิมพ์เอกสาร / PDF</button></div><ProfitDocument data={data} report={result?.profitReport}/></section>}
  {tab==="summary"&&<section className="summaryGrid"><div className="panel"><h2>สรุปค่าใช้จ่าย</h2>{[["รวมค่าใช้จ่าย",result?.totals.baseBeforeDeduction],["หักก่อน VAT",result?.totals.deductionBeforeVat],["ฐานคิด VAT",result?.totals.vatBase],["VAT 7%",result?.totals.vat],["รวม VAT",result?.totals.includingVat],["หักหลัง VAT",result?.totals.deductionAfterVat]].map(([l,v])=><div className="line" key={String(l)}><span>{l}</span><b>฿{money(v as number)}</b></div>)}<div className="line total"><span>ยอดชำระทั้งสิ้น</span><b>฿{money(result?.totals.payable)}</b></div></div><div className="panel"><h2>กำไรและ มท.</h2><div className="line"><span>กำไรขั้นต้น</span><b>฿{money(result?.totals.grossProfit)}</b></div><div className="line"><span>มท. (ไม่คิด VAT)</span><b>฿{money(result?.totals.mtBase)}</b></div><div className="line"><span>มท.7 ก่อน VAT</span><b>฿{money(result?.totals.mt7Base)}</b></div><div className="line"><span>VAT มท.7</span><b>฿{money(result?.totals.mt7Vat)}</b></div><div className="line total"><span>รวม มท./มท.7</span><b>฿{money(result?.totals.mtGrandTotal)}</b></div></div></section>}
  {error&&<div className="toast">{error}</div>}
 </main>
}

function WorkTemplateWorkspace({project}:{project:Record<string,string>}){
 const [templates,setTemplates]=useState<WorkTemplate[]>([]);const [selectedId,setSelectedId]=useState("");const [items,setItems]=useState<WorkItem[]>([]);const [result,setResult]=useState<any>(null);
 const selected=templates.find(template=>template.id===(selectedId||templates[0]?.id));
 useEffect(()=>{fetch(`${API}/api/work-templates`).then(response=>response.json()).then((data:WorkTemplate[])=>{setTemplates(data);if(data[0]){setSelectedId(data[0].id);setItems(data[0].items);}})},[]);
 useEffect(()=>{if(!items.length){setResult(null);return;}const timer=setTimeout(()=>fetch(`${API}/api/work-templates/calculate`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(items)}).then(response=>response.json()).then(setResult),120);return()=>clearTimeout(timer)},[items]);
 const choose=(template:WorkTemplate)=>{setSelectedId(template.id);setItems(template.items.map(item=>({...item})));};
 const update=(id:string,key:keyof WorkItem,value:string|number)=>setItems(current=>current.map(item=>item.id===id?{...item,[key]:value}:item));
 const add=()=>setItems(current=>[...current,{id:crypto.randomUUID(),description:"",quantity:1,unitPrice:0,labor:0}]);
 const remove=(item:WorkItem)=>{if(window.confirm(`ลบรายการ “${item.description}” หรือไม่?`))setItems(current=>current.filter(row=>row.id!==item.id));};
 if(!selected)return <section className="panel">กำลังโหลด template…</section>;
 return <section className="workTemplateWorkspace">
  <div className="templatePicker screenOnly"><label><span>เลือก Template</span><select value={selected.id} onChange={event=>{const template=templates.find(row=>row.id===event.target.value);if(template)choose(template)}}>{["ชุด A","ชุด B","กำหนดเอง"].map(group=><optgroup key={group} label={group}>{templates.filter(template=>template.group===group).map(template=><option key={template.id} value={template.id}>{template.sheetName} — {template.title}</option>)}</optgroup>)}</select></label><div className="templateActions"><button type="button" className="ghost" onClick={add}>+ เพิ่มรายการ</button><button type="button" onClick={()=>window.print()}>พิมพ์ / บันทึก PDF</button></div></div>
  <article className="workTemplatePaper"><h1>{selected.title}</h1><div className="workMeta"><span>ชื่องาน {project.jobName}</span><span>เลขแผนผัง {project.drawingNo}</span></div>
   <div className="workTable">
    <div className="workRow workHead"><span>รายการ</span><span>จำนวน</span><span>หน่วยละ</span><span>รวม</span><span>ราคา กฟภ.</span><span>ค่าแรง</span><span className="screenOnly"></span></div>
    {items.map(item=><div className="workRow" key={item.id}><div className="workDescription"><input placeholder="พิมพ์ชื่อรายการ" value={item.description} onChange={e=>update(item.id,"description",e.target.value)}/></div><input className="num" type="number" value={item.quantity} onChange={e=>update(item.id,"quantity",Number(e.target.value))}/><MoneyInput value={item.unitPrice} onChange={value=>update(item.id,"unitPrice",Number(value||0))}/><b>{money(item.quantity*item.unitPrice)}</b><b>{money(item.quantity*item.unitPrice)}</b><MoneyInput value={item.labor} onChange={value=>update(item.id,"labor",Number(value||0))}/><button className="screenOnly" onClick={()=>remove(item)}>ลบ</button></div>)}
    <div className="workSummaryRow workSummarySplit"><span>รวม</span><b>{money(result?.material)}</b><b>{money(result?.labor)}</b><i className="screenOnly"></i></div>
    <div className="workSummaryRow"><span>รวมค่าพัสดุ + ค่าแรง</span><b>{money(result?.subtotal)}</b><i className="screenOnly"></i></div>
    <div className="workSummaryRow"><span>ค่าดำเนินการ 7.5%</span><b>{money(result?.operation)}</b><i className="screenOnly"></i></div>
    <div className="workSummaryRow grand"><span>รวมทั้งสิ้น</span><b>{money(result?.grandTotal)}</b><i className="screenOnly"></i></div>
   </div>
   {selected.note&&<div className="workNote"><b>*** หมายเหตุ ***</b><span>{selected.note}</span>{selected.quote&&<span>ตามใบเสนอราคา เลขที่ {selected.quote}</span>}</div>}
   <div className="workSign"><div><b>ผู้สำรวจ</b><span>{project.surveyor}</span></div><div><b>ผู้ประมาณการ</b><span>{project.estimator}</span></div><div><b>ผู้ตรวจสอบ</b><span>{project.reviewer}</span></div></div>
  </article>
 </section>
}

function ProfitDocument({data,report}:{data:Estimate;report:ProfitReport|undefined}){
 const rows=report?.rows??[];
 const address=[data.project.jobName,data.project.address&&`บ้านเลขที่ ${data.project.address}`,data.project.subdistrict&&`ตำบล${data.project.subdistrict}`,data.project.district&&`อำเภอ${data.project.district}`,data.project.province&&`จังหวัด${data.project.province}`,data.project.postalCode].filter(Boolean).join(" ");
 return <article className="profitPaper">
  <h1>สรุปค่าใช้จ่ายในการประมาณการก่อสร้างระบบจำหน่าย</h1>
  <div className="profitMeta"><b>งานที่</b><span></span><b>เลขที่แบบ</b><span>{data.project.drawingNo}</span><span className="profitRegion">เขต 3 ภาคใต้</span><i></i><b>ชื่องาน</b><span className="job">{address}</span></div>
  <div className="profitNotice">*** รายละเอียดแสดงการคิดกำไรขั้นต้น (คิดเฉพาะงานที่ก่อสร้างแล้วเสร็จทรัพย์สินเป็นของผู้ใช้ไฟ) ***</div>
  <table className="profitTable"><colgroup><col/><col/><col/><col/><col/><col/><col/><col/></colgroup><thead><tr className="headingRow"><th colSpan={3} rowSpan={2} className="departmentHeading">แผนกงาน</th><th>ต้นทุน</th><th>กำไรขั้นต้น</th><th>กำไรขั้นต้น</th><th>หมายเหตุ</th><th>รวมทั้งสิ้น</th></tr><tr className="unitRow"><th>บาท</th><th>ร้อยละ (%)</th><th>บาท</th><th>ค่าวัสดุอุปกรณ์</th><th>บาท</th></tr></thead><tbody>
   {rows.map((row,i)=><tr key={row.id} className={i===rows.length-1?"lastItem":""}><td colSpan={3} className={row.description.length>30?"longText":""} style={{fontSize:`${profitTextSize(row.description)}pt`}}>{row.description}</td><td>{money(row.cost)}</td><td>{money(row.rate*100)}%</td><td>{money(row.profit)}</td><td></td><td>{money(row.total)}</td></tr>)}
   {!rows.length&&<tr className="emptyProfit"><td colSpan={3}></td><td></td><td></td><td></td><td></td><td></td></tr>}
  </tbody><tfoot><tr><th colSpan={3}>รวม</th><td>{money(report?.totalCost)}</td><td></td><td>{money(report?.totalProfit)}</td><td></td><td>{money(report?.totalWithProfit)}</td></tr><tr><th colSpan={3}>กำไรขั้นต้น</th><td></td><td></td><td>{money(report?.totalProfit)}</td><th>บาท</th><td></td></tr></tfoot></table>
  <div className="profitSign"><div><b>ผู้สำรวจ</b><span>{data.project.surveyor}</span></div><div><b>ผู้ประมาณการ</b><span>{data.project.estimator}</span></div><div><b>ผู้ตรวจสอบ</b><span>{data.project.reviewer}</span></div></div>
 </article>
}

function SummaryWorkspace({data,summary,subtopic,onBack}:{data:Estimate;summary:SummaryReport;subtopic:SubtopicReport;onBack:()=>void}){
 const [sheet,setSheet]=useState<"summary_report"|"summary_subtopic_table">("summary_report");
 return <section className="summaryWorkspace"><div className="summaryToolbar"><button className="ghost" onClick={onBack}>← กลับ tableexpend</button><div className="summarySheetTabs"><button className={sheet==="summary_report"?"active":"ghost"} onClick={()=>setSheet("summary_report")}>summary_report</button><button className={sheet==="summary_subtopic_table"?"active":"ghost"} onClick={()=>setSheet("summary_subtopic_table")}>summary_subtopic_table</button></div><button onClick={()=>window.print()}>พิมพ์หน้านี้ / PDF</button></div>{sheet==="summary_report"?<SummaryDocument data={data} report={summary}/>:<SubtopicDocument report={subtopic}/>}</section>
}

function SummaryDocument({data,report}:{data:Estimate;report:SummaryReport}){
 const address=[data.project.jobName,data.project.address&&`บ้านเลขที่ ${data.project.address}`,data.project.subdistrict&&`ตำบล${data.project.subdistrict}`,data.project.district&&`อำเภอ${data.project.district}`,data.project.province&&`จังหวัด${data.project.province}`,data.project.postalCode].filter(Boolean).join(" ");
 const before=report.deductionItems.filter(item=>item.mode===3); const after=report.deductionItems.filter(item=>item.mode===2); const info=report.deductionItems.filter(item=>item.mode===1);
 return <article className="summaryPaper"><h1>สรุปค่าใช้จ่ายในการประมาณการก่อสร้างระบบจำหน่าย</h1><div className="summaryMeta"><b>งานที่</b><span></span><b>เลขที่แบบ</b><span>{data.project.drawingNo}</span><div className="summaryRegion"><b>เขต 3</b><b>ภาคใต้</b></div><i></i><b>ชื่องาน</b><span className="job">{address}</span></div><div className="wbs">{data.project.wbs}</div><div className="summaryBody">
  {report.sections.map(section=><section key={section.id} className="summarySection"><h2>{section.title}</h2>{section.items.map((item,index)=><div className="summaryItem" key={item.id}><span>{index+1}.</span><span>{item.description}</span><b>{money(item.amount)}</b><span>บาท</span></div>)}<div className="summarySubtotal"><span>รวมเงิน</span><b>{money(section.total)}</b><span>บาท</span></div></section>)}
  <SummaryAmount label="รวมเงินค่าใช้จ่ายคิดจากผู้ใช้ไฟ" value={report.totals.expense} noLine/>
  {before.map(item=><SummaryAmount key={item.id} label={item.description} value={item.amount} deduction/>)}
  <SummaryAmount label="ภาษีมูลค่าเพิ่ม 7 %" value={report.totals.vat} noLine/>
  <SummaryAmount label="รวมเงินค่าใช้จ่ายคิดจากผู้ใช้ไฟ รวมภาษีมูลค่าเพิ่ม" value={report.totals.includingVat} strong/>
  {after.map(item=><SummaryAmount key={item.id} label={item.description} value={item.amount} deduction/>)}
  {!!after.length&&<SummaryAmount label="ยอดชำระทั้งสิ้นที่ผู้ใช้ไฟต้องชำระ" value={report.totals.payable} strong/>}
  {info.map(item=><SummaryAmount key={item.id} label={item.description} value={item.amount} deduction/>)}
 </div><p className="summaryNote">หมายเหตุ ยังไม่รวมค่าธรรมเนียมต่าง ๆ ขอให้คิดค่าธรรมเนียมตามระเบียบของ กฟภ.ที่กำหนด นอกโปรแกรมประมาณการ ฯ</p><div className="summarySign"><div><b>ผู้สำรวจ</b><span>{data.project.surveyor}</span></div><div><b>ผู้ประมาณการ</b><span>{data.project.estimator}</span></div><div><b>ผู้ตรวจสอบ</b><span>{data.project.reviewer}</span></div></div></article>
}

function SummaryAmount({label,value,strong=false,deduction=false,noLine=false}:{label:string;value:number;strong?:boolean;deduction?:boolean;noLine?:boolean}){
 return <div className={`summaryAmount ${strong?"strong":""} ${deduction?"deduction":""} ${noLine?"noLine":""}`}><span>{label}</span><b>{money(deduction?Math.abs(value):value)}</b><span>บาท</span></div>
}

function SubtopicDocument({report}:{report:SubtopicReport}){
 return <article className="subtopicPaper"><h1>summary_subtopic_table</h1><div className="subtopicTable">{report.chargeSections.map(section=><section key={section.id}><h2>{section.title}</h2>{section.items.map(item=><div key={item.id}><span>{item.description}</span><b>{money(item.amount)}</b><span>บาท</span></div>)}</section>)}<SummaryAmount label="รวม" value={report.totals.expense}/><SummaryAmount label="ภาษีมูลค่าเพิ่ม 7 %" value={report.totals.vat}/><SummaryAmount label="ยอดรวมที่ผู้ใช้ไฟต้องชำระ" value={report.totals.payable} strong/><SummaryAmount label="ยอดรวมที่ผู้ใช้ไฟต้องชำระ รวมภาษีมูลค่าเพิ่ม 7 %" value={report.totals.includingVat} strong/>{report.peaSections.map(section=><section key={section.id}><h2>{section.title}</h2>{section.items.map(item=><div key={item.id}><span>{item.description}</span><b>{money(item.amount)}</b><span>บาท</span></div>)}</section>)}<SummaryAmount label="รวม" value={report.totals.pea}/></div></article>
}

const hotlineDefaults:HotlineInput={regularDays:1,regularRate:21500,holidayDays:"",holidayRate:18000,hotstickDays:"",hotstickRate:2600,bucket2233Days:1,bucket2233Rate:7000,bucket115Days:"",bucket115Rate:10000,waterTruckDays:"",waterTruckRate:2000,allowanceDays:1,allowanceRate:2000,lodgingDays:"",lodgingRate:4500,hotstickKm:"",hotstickFuelPrice:"",bucketKm:24,bucketFuelPrice:40.8,bucketWaterKm:"",bucketWaterFuelPrice:"",waterTruckKm:"",waterTruckFuelPrice:""};

function HotlineWorkspace({project,onApply}:{project:Record<string,string>;onApply:(total:number)=>void}){
 const [input,setInput]=useState<HotlineInput>(hotlineDefaults); const [result,setResult]=useState<HotlineResult|null>(null); const [message,setMessage]=useState("กำลังเชื่อมยอดกับรายการประมาณการอัตโนมัติ…");
 const set=(key:keyof HotlineInput,value:HotlineValue)=>setInput(current=>({...current,[key]:value}));
 const normalized=()=>Object.fromEntries(Object.entries(input).map(([key,value])=>[key,value===""?0:value]));
 useEffect(()=>{const timer=setTimeout(async()=>{try{const response=await fetch(`${API}/api/hotline/calculate`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(normalized())});if(response.ok)setResult(await response.json());}catch{}},120);return()=>clearTimeout(timer)},[input]);
 useEffect(()=>{if(!result)return;onApply(result.total);setMessage(`เชื่อมยอด ${money(result.total)} บาทกับรายการประมาณการอัตโนมัติแล้ว`);},[result?.total]);
 const apply=()=>{if(!result){setMessage("ยังคำนวณยอดไม่ได้");return;}onApply(result.total);setMessage(`ส่งยอด ${money(result.total)} บาทกลับไปยัง tableexpend แล้ว`);};
 const calculate=apply;
 const address=[project.jobName,project.address&&`บ้านเลขที่ ${project.address}`,project.subdistrict&&`ตำบล${project.subdistrict}`,project.district&&`อำเภอ${project.district}`,project.province&&`จังหวัด${project.province}`,project.postalCode].filter(Boolean).join(" ");
 return <section className="hotlineWorkspace"><div className="hotlineToolbar"><span>{message||"ยอดค่าบริการฮอทไลน์เชื่อมกลับรายการประมาณการอัตโนมัติ"}</span><button type="button" onClick={()=>window.print()}>พิมพ์ / บันทึก PDF</button></div><article className="hotlinePaper"><h1>การคิดประมาณการค่าใช้จ่ายการให้บริการด้านฮอทไลน์สำหรับผู้ใช้ไฟที่เป็นลูกค้า</h1><h2>ของ กฟภ. หน่วยฮอทไลน์ สังกัด กฟส.หาดใหญ่</h2><div className="hotlineJob"><b>ชื่องาน</b><span>{address}</span></div><div className="hotlineHead"><b></b><b>เลือก</b><b>รายละเอียด</b><b>จำนวน/ระยะทาง</b><b>อัตรา</b><b>เป็นเงิน (บาท)</b></div>
  <HotlineSection no="1" title="ค่าแรงพนักงานฮอทไลน์"><HotlineRow label="กรณีปฏิบัติงานวันปกติ" qty={input.regularDays} rate={input.regularRate} amount={result?.rows.regularLabor} onQty={v=>set("regularDays",v)} onRate={v=>set("regularRate",v)}/><HotlineRow label="กรณีปฏิบัติงานวันหยุด หรือวันหยุดตามประกาศ กฟภ." qty={input.holidayDays} rate={input.holidayRate} amount={result?.rows.holidayLabor} onQty={v=>set("holidayDays",v)} onRate={v=>set("holidayRate",v)}/></HotlineSection>
  <HotlineSection no="2" title="ค่าเครื่องมือและยานพาหนะ"><HotlineRow label="ฮอทสติก" qty={input.hotstickDays} rate={input.hotstickRate} amount={result?.rows.hotstickTool} onQty={v=>set("hotstickDays",v)} onRate={v=>set("hotstickRate",v)}/><HotlineRow label="กระเช้า ระบบ 22-33 KV" qty={input.bucket2233Days} rate={input.bucket2233Rate} amount={result?.rows.bucket2233} onQty={v=>set("bucket2233Days",v)} onRate={v=>set("bucket2233Rate",v)}/><HotlineRow label="กระเช้า ระบบ 115 KV" qty={input.bucket115Days} rate={input.bucket115Rate} amount={result?.rows.bucket115} onQty={v=>set("bucket115Days",v)} onRate={v=>set("bucket115Rate",v)}/><HotlineRow label="รถบรรทุกน้ำ" qty={input.waterTruckDays} rate={input.waterTruckRate} amount={result?.rows.waterTruckTool} onQty={v=>set("waterTruckDays",v)} onRate={v=>set("waterTruckRate",v)}/></HotlineSection>
  <HotlineCalculated no="3" label="ค่าเบ็ดเตล็ด คิด 5% ของ (1+2)" value={result?.rows.miscellaneous}/><HotlineCalculated no="4" label="ค่าใช้จ่ายในการดำเนินการ คิด 7.5% ของ (1+2+3)" value={result?.rows.operation}/>
  <HotlineSection no="5" title="ค่าใช้จ่ายในการปฏิบัติงานของพนักงาน"><HotlineRow label="ค่าเบี้ยเลี้ยง" qty={input.allowanceDays} rate={input.allowanceRate} amount={result?.rows.allowance} onQty={v=>set("allowanceDays",v)} onRate={v=>set("allowanceRate",v)}/><HotlineRow label="ค่าที่พัก" qty={input.lodgingDays} rate={input.lodgingRate} amount={result?.rows.lodging} onQty={v=>set("lodgingDays",v)} onRate={v=>set("lodgingRate",v)}/></HotlineSection>
  <HotlineSection no="6" title="ค่าใช้จ่ายของรถยนต์ที่ใช้ปฏิบัติงาน"><HotlineRow label="ฮอทสติก (ระยะทาง × ราคาน้ำมัน × 1)" qty={input.hotstickKm} rate={input.hotstickFuelPrice} amount={result?.rows.hotstickVehicle} onQty={v=>set("hotstickKm",v)} onRate={v=>set("hotstickFuelPrice",v)}/><HotlineRow label="กระเช้า ระบบ 22-33 / 115 KV (× 2)" qty={input.bucketKm} rate={input.bucketFuelPrice} amount={result?.rows.bucketVehicle} onQty={v=>set("bucketKm",v)} onRate={v=>set("bucketFuelPrice",v)}/><HotlineRow label="กระเช้าพร้อมรถพ่วงฉีดน้ำ (× 2.2)" qty={input.bucketWaterKm} rate={input.bucketWaterFuelPrice} amount={result?.rows.bucketWaterVehicle} onQty={v=>set("bucketWaterKm",v)} onRate={v=>set("bucketWaterFuelPrice",v)}/><HotlineRow label="รถบรรทุกน้ำ (× 1)" qty={input.waterTruckKm} rate={input.waterTruckFuelPrice} amount={result?.rows.waterTruckVehicle} onQty={v=>set("waterTruckKm",v)} onRate={v=>set("waterTruckFuelPrice",v)}/></HotlineSection>
  <HotlineCalculated no="7" label="กำไรขั้นต้น คิด 30% ของ (1+2+3+4+5+6)" value={result?.rows.grossProfit}/><div className="hotlineTotal"><b>รวมค่าใช้จ่ายทั้งสิ้น</b><b>{money(result?.total)}</b><b>บาท</b></div><p>* หมายเหตุ ไม่รวมภาษีมูลค่าเพิ่ม</p><div className="hotlineSign"><span>ผู้สำรวจ</span><b>{project.surveyor}</b><span>ผู้ประมาณการ</span><b>{project.estimator}</b><span>ผู้ตรวจสอบ</span><b>{project.reviewer}</b></div></article></section>
}

function HotlineSection({no,title,children}:{no:string;title:string;children:React.ReactNode}){return <section className="hotlineSection"><h3><span>{no}</span>{title}</h3>{children}</section>}
function MoneyInput({value,onChange}:{value:HotlineValue;onChange:(value:HotlineValue)=>void}){const [text,setText]=useState(moneyInput(value));const [editing,setEditing]=useState(false);useEffect(()=>{if(!editing)setText(moneyInput(value));},[value,editing]);return <input type="text" inputMode="decimal" placeholder="ไม่ระบุ" value={text} onFocus={()=>{setEditing(true);setText(value===""?"":String(value));}} onChange={e=>{const raw=e.target.value;setText(raw);const parsed=parseMoneyInput(raw);if(parsed===""||Number.isFinite(parsed))onChange(parsed);}} onBlur={()=>{setEditing(false);setText(moneyInput(value));}}/>}
function HotlineRow({label,qty,rate,amount,onQty,onRate}:{label:string;qty:HotlineValue;rate:HotlineValue;amount?:number;onQty:(v:HotlineValue)=>void;onRate:(v:HotlineValue)=>void}){const enabled=qty!=="";const value=(raw:string):HotlineValue=>raw===""?"":Number(raw);return <div className={`hotlineRow ${enabled?"enabled":""}`}><span className="hotlineIndent"></span><label className="hotlineCheck"><input type="checkbox" checked={enabled} onChange={e=>onQty(e.target.checked?1:"")}/></label><span>{label}</span><input type="number" placeholder="ไม่ระบุ" value={qty} onChange={e=>onQty(value(e.target.value))}/><MoneyInput value={rate} onChange={onRate}/><b>{enabled?money(amount):"-"}</b></div>}
function HotlineCalculated({no,label,value}:{no:string;label:string;value?:number}){return <div className={`hotlineCalculated ${no==="3"||no==="4"||no==="7"?"emphasis":""}`}><b>{no}</b><span>{label}</span><b>{money(value)}</b></div>}
